// GENERADO desde datos/*.yaml — no editar directamente

export const CFG = {
    meta: {
        titulo: 'El Abismo',
        itemInventario: '',
        timeoutExito: 1500,
    },
    canvas: {
        anchoBase: 480,
        altoBase: 270,
    },
    tiles: {
        tamano: 16,
        tipos: {
            VACIO: 0,
            SUELO: 1,
            PLATAFORMA: 2,
            ABISMO: 3,
            SPAWN_JUGADOR: 4,
            SPAWN_ENEMIGO: 5,
            SPAWN_BOSS: 6,
            META: 7,
        },
    },
    fisicas: {
        gravedad: 0.5,
        velocidadMaxCaida: 8,
        velocidadJugador: 2.5,
        fuerzaSalto: -7.5,
        fuerzaStompReboteBajo: -3,
        fuerzaStompReboteAlto: -6,
        coyoteTime: 6,
        jumpBuffer: 6,
        invulnerabilidad: 60,
        knockbackX: 3,
        knockbackY: -4,
        jumpCutFactor: 0.4,
        invulPostStomp: 12,
    },
    enemigos: {
        stompMargenRatio: 0.3,
        stompVyMinBase: 1.5,
        stompVyMinEscalaFactor: 0.5,
        cooldownAtaque: 60,
        invulStomp: 30,
        stunStomp: 10,
    },
    boss: {
        fasesCambio: [0.66, 0.33],
        velocidadFases: [1, 1.4],
    },
    render: {
        colorSuelo: '#2a2a5e',
        colorPlataforma: '#3a3a7e',
        colorEnemigo: '#e94560',
        colorBoss: '#bb86fc',
    },
    escalado: {
        estaturaRef: 1.55,
        escalaMin: 0.45,
        escalaMax: 1.45,
        hitboxBaseW: 12,
        hitboxBaseH: 14,
        spriteBaseW: 48,
        spriteBaseH: 60,
        velAttrMin: 3,
        velAttrMax: 9,
        velPlatMin: 1,
        velPlatMax: 3,
        fuerzaSaltoBase: -7.5,
        fuerzaSaltoFactor: 0.3,
    },
    camara: {
        shakeDecay: 0.9,
    },
    sprites: {
        jugadorIdleVel: 30,
        jugadorCorrerVel: 6,
        jugadorAgacharseVel: 20,
    },
};
