// GENERADO desde datos/*.yaml — no editar directamente

export const CFG = {
    meta: {
        titulo: 'El Duelo',
        timeoutExito: 1500,
    },
    canvas: {
        anchoBase: 480,
        altoBase: 270,
    },
    arena: {
        sueloY: 230,
        limiteIzq: 30,
        limiteDer: 450,
        separacionInicial: 200,
    },
    fisicas: {
        gravedad: 0.55,
        velocidadMaxCaida: 9,
        fuerzaSalto: -9.5,
        velocidadBase: 2.5,
        retrocesoGolpe: 4,
        retrocesoGolpeFuerte: 6,
        retrocesoVertical: -2,
    },
    escalado: {
        estaturaRef: 1.55,
        escalaMin: 0.55,
        escalaMax: 1.35,
        hitboxBaseW: 28,
        hitboxBaseH: 48,
        spriteBaseW: 48,
        spriteBaseH: 60,
        velAttrMin: 3,
        velAttrMax: 9,
        velMin: 1.5,
        velMax: 3.5,
    },
    combate: {
        tiempoRonda: 90,
        bloqueoReduccion: 0.3,
        agacharsePorcentajeHitbox: 0.5,
        invulnerabilidad: 30,
        ataqueRapidoCooldown: 20,
        ataqueFuerteCooldown: 40,
        ataqueRapidoDuracion: 12,
        ataqueFuerteDuracion: 18,
        ataqueRapidoDanoBase: 8,
        ataqueFuerteDanoBase: 15,
        ataqueRapidoAlcance: 35,
        ataqueFuerteAlcance: 40,
        ataqueAltoOffset: 0.2,
        ataqueAltoAlcanceY: 0.5,
    },
    mecanicas: {
        parryVentana: 8,
        parryAturdimiento: 25,
        parryBoostDano: 1.4,
        parryBoostDuracion: 90,
        comboTimer: 60,
        comboMultiplicadores: [1, 1.15, 1.3, 1.5],
        aereoMultDano: 1.5,
        aereoCooldown: 30,
        guardiaMax: 4,
        guardiaCostoRapido: 1,
        guardiaCostoFuerte: 2,
        guardiaRegenIntervalo: 120,
        guardiaRotaStun: 45,
    },
    ia: {
        reaccionMin: 10,
        reaccionMax: 40,
        distanciaOptima: 45,
        probBloqueo: 0.3,
        probAtaque: 0.02,
        probSalto: 0.005,
        agresividad: {
            esbirro: 0.6,
            elite: 1,
            pesadilla: 1.5,
        },
        probParry: 0.15,
        probAtaqueAereo: 0.008,
    },
    render: {
        colorSuelo: '#2a1a3e',
        colorFondo: '#0d0620',
        colorArenaClaro: '#3d2560',
        colorBarraJugador: '#5eeadb',
        colorBarraEnemigo: '#e94560',
        colorTimer: '#f0e6d3',
    },
    sprites: {
        idleVel: 30,
        correrVel: 6,
        ataqueVel: 6,
        agacharseVel: 6,
        golpeadoVel: 15,
    },
    pantallas: {
        countdownSegundos: 3,
        resultadoSegundos: 3,
    },
    textos: {
        pelea: '¡Pelea!',
        victoria: '¡Victoria!',
        derrota: '¡Derrota!',
        tiempoAgotado: '¡Tiempo!',
        ko: '¡KO!',
    },
};
