// GENERADO desde datos/*.yaml — no editar directamente

export const CFG = {
    meta: {
        titulo: 'Habitación 1 — El Laberinto',
        itemInventario: 'llave-habitacion-2',
        timeoutExito: 1500,
    },
    textos: {
        indicadorBusqueda: 'Encuentra la llave',
        indicadorLlaveObtenida: '¡Llave obtenida! Vuelve a la salida',
        toastLlave: '¡Llave encontrada!',
        mensajeExito: '¡Escapaste con la llave!',
        toastElite: '¡{nombre} ha aparecido!',
    },
    laberinto: {
        filas: 17,
        columnas: 17,
        atajos: 8,
    },
    jugador: {
        tamBase: 22,
        velocidadBase: 3,
        velocidadReferencia: 7,
        margenColision: 2,
        toleranciaEsquina: 8,
        escalaVisualBase: 1.45,
        estaturaReferencia: 1.55,
    },
    trampasFuego: {
        cantidadMin: 3,
        cantidadMax: 5,
        distanciaMinEntrada: 3,
        periodoMin: 1500,
        periodoMax: 3500,
        desfaseMax: 3000,
        cooldown: 1000,
        danoMin: 5,
        danoMax: 10,
    },
    trampasLentitud: {
        cantidadMin: 2,
        cantidadMax: 3,
        distanciaMinEntrada: 3,
        periodoMin: 2000,
        periodoMax: 4000,
        desfaseMax: 3000,
        cooldown: 500,
        reduccionMin: 0.3,
        reduccionMax: 0.6,
        duracionMin: 3000,
        duracionMax: 4000,
    },
    trasgo: {
        tamBase: 20,
        velocidadBase: 2,
        cooldownBaseAtaque: 10500,
        intervaloPathfinding: 500,
        posicionDistMin: 0.4,
        posicionDistMax: 0.7,
    },
    villanoElite: {
        tamBase: 22,
        velocidadBase: 2,
        velocidadReferencia: 6,
        countdown: 15,
        intervaloPathfinding: 500,
        posicionDistMin: 0.5,
        posicionDistMax: 0.8,
        escalaVisualBase: 1.45,
        estaturaReferencia: 1.55,
    },
    render: {
        tamCeldaBase: 30,
    },
};
